---
title: "week1-discussion"
author: "joshua paul cohen"
format: html
date: last-modified
---

```{r}
rm(list = ls())
```

```{r}
library(tidyverse)
library(janitor)
library(usdata)
```

```{r}
frack <- read_csv(here::here('weeks', 'week_1', 'data', 'registryupload_1.csv'))
```

```{r}
# cleaning
#frack_clean1 <- frack %>% clean_names() %>% mutate(job_start_date = str_remove(job_start_date, ' AM'))
#frack_clean1$job_start_date <- frack_clean1$job_start_date %>% mdy_hms()



frack_clean <- frack %>% clean_names() %>% 
  mutate(job_start_date = str_remove(job_start_date, ' AM')) %>% 
  mutate(datetime_start = mdy_hms(job_start_date)) %>% 
  mutate(year = year(datetime_start)) %>% 
  select(datetime_start, year, state_name, well_name, total_base_water_volume) %>% 
  mutate(state_name = str_to_title(state_name)) %>% 
  filter(!str_detect(state_name, pattern = '\\?')) %>% 
  mutate(state_name =ifelse(str_length(state_name) <= 2, 
                            abbr2state(state_name), 
                            state_name)) %>%
  mutate(state_name = case_when(
    state_name == "Colordao" ~ "Colorado",
    state_name == "Loiusiana" ~ "Louisiana",
    state_name == "Louisianna" ~ "Louisiana",
    state_name == "Lousiana" ~ "Louisiana",
    state_name == "New Mexcio" ~ "New Mexico",
    state_name == "Norh Dakota" ~ "North Dakota",
    state_name == "Norht Dakota" ~ "North Dakota",
    state_name == "North  Dakota" ~ "North Dakota",
    state_name == "North Dakata" ~ "North Dakota",
    state_name == "North Dakotta" ~ "North Dakota",
    state_name == "Noth Dakota" ~ "North Dakota",
    state_name == "Pennslvania" ~ "Pennsylvania",
    state_name == "Pennsylavania" ~ "Pennsylvania",
    state_name == "Pennsylvanya" ~ "Pennsylvania",
    state_name == "Penssylvania" ~ "Pennsylvania",
    state_name == "Texasa" ~ "Texas",
    state_name == "Texs" ~ "Texas", 
    state_name == "West Viginia" ~ "West Virginia",
    state_name == "Wyominng" ~ "Wyoming", 
    TRUE ~ state_name # copy over rest of state names from as-is
  )) %>% 
  filter(!state_name %in% c('Beaver', 'Beckham', 'Harper', 'Hemphill', 'Midland', 'Red River', 'Roosevelt', 'Rusk', 'State', 'Ward'))
```

